### ISSUE TITLE
'ffdl', 'install', '--add-path' returned non-zero exit status 2.

### ISSUE THREAD

**Issue by tin2tin** [python-ffmpegio/python-ffmpeg-downloader#5]
I'm trying to install this from within Blender, but I'm getting this error:
`subprocess.CalledProcessError: Command '['C:\\Program Files\\Blender Foundation\\Blender 3.6\\3.6\\python\\bin\\python.exe', 'ffdl', 'install', '--add-path']' returned non-zero exit status 2.`

This is how I try to install it: 

```
import subprocess, site, sys

app_path = site.USER_SITE
if app_path not in sys.path:
    sys.path.append(app_path)
pybin = sys.executable

try:
    exec("import ffmpeg_downloader")
except ModuleNotFoundError:
    subprocess.check_call(
        [
            pybin,
            "-m",
            "pip",
            "install",
            "ffmpeg-downloader",
            "--user",
        ]
    )
    subprocess.check_call(
        [
            pybin,
            "ffdl",
            "install",
            "--add-path",
        ]
    )
```

**Comment by tikuma-lsuhsc** [comment]
@tin2tin  - Is there any error message? What does the `stdout`/`stderr` properties of the `CompletedProcess` returned by the `ffdl` call?

**Comment by tin2tin** [comment]
This is the full log. What I need is to have ffmpeg on PATH. Looks like `ffdl install `fails?

```
Collecting ffmpeg-downloader
  Using cached ffmpeg_downloader-0.2.0-py3-none-any.whl (27 kB)
Requirement already satisfied: requests in c:\users\45239\appdata\roaming\python\python310\site-packages (from ffmpeg-downloader) (2.28.1)
Requirement already satisfied: tqdm>=4.40.0 in c:\program files\blender foundation\blender 3.6\3.6\python\lib\site-packages (from ffmpeg-downloader) (4.66.1)
Requirement already satisfied: appdirs in c:\users\45239\appdata\roaming\python\python310\site-packages (from ffmpeg-downloader) (1.4.4)
Requirement already satisfied: packaging in c:\users\45239\appdata\roaming\python\python310\site-packages (from ffmpeg-downloader) (23.2)
Requirement already satisfied: colorama in c:\program files\blender foundation\blender 3.6\3.6\python\lib\site-packages (from tqdm>=4.40.0->ffmpeg-downloader) (0.4.6)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\program files\blender foundation\blender 3.6\3.6\python\lib\site-packages (from requests->ffmpeg-downloader) (2.0.10)
Requirement already satisfied: idna<4,>=2.5 in c:\program files\blender foundation\blender 3.6\3.6\python\lib\site-packages (from requests->ffmpeg-downloader) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\program files\blender foundation\blender 3.6\3.6\python\lib\site-packages (from requests->ffmpeg-downloader) (1.26.8)
Requirement already satisfied: certifi>=2017.4.17 in c:\program files\blender foundation\blender 3.6\3.6\python\lib\site-packages (from requests->ffmpeg-downloader) (2021.10.8)
Installing collected packages: ffmpeg-downloader
  WARNING: The script ffdl.exe is installed in 'C:\Users\45239\AppData\Roaming\Python\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed ffmpeg-downloader-0.2.0
C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\bin\python.exe: can't open file 'C:\\Program Files\\Blender Foundation\\Blender 3.6\\ffdl': [Errno 2] No such file or directory
Error: Python: Traceback (most recent call last):
  File "C:\Users\45239\Documents\unet_01.blend\Text.004", line 9, in <module>
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'ffmpeg_downloader'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\45239\Documents\unet_01.blend\Text.004", line 21, in <module>
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Program Files\\Blender Foundation\\Blender 3.6\\3.6\\python\\bin\\python.exe', 'ffdl', 'install', 'add-path']' returned non-zero exit status 2.
```

**Comment by tikuma-lsuhsc** [comment]
```
WARNING: The script ffdl.exe is installed in 'C:\Users\45239\AppData\Roaming\Python\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
```

This seems to be the primary problem. You can try inserting

```
sys.path.append('C:\Users\45239\AppData\Roaming\Python\Python310\Scripts')
```

before calling `ffdl`.

Now, `ffdl install` is interactive. Does Blender let you do cli i/o?

**Comment by tin2tin** [comment]
Checking is the ffdl is in Scripts, and yes it is there:
![image](https://github.com/python-ffmpegio/python-ffmpeg-downloader/assets/1322593/85574df3-4f29-4543-84af-9acaaedcc1fc)

But doing this gives an access denied error:
```
pybin = 'C:/Users/45239/AppData/Roaming/Python/Python310/Scripts'
subprocess.check_call(
    [
        pybin,
        "ffdl",
        "install",
        "--add-path",
    ]
)
```

I am running Blender as admin.

**Comment by tikuma-lsuhsc** [comment]
Right, my bad. This message

```
ModuleNotFoundError: No module named 'ffmpeg_downloader'
```

indicates that the `ffdl` script is in the path but not what it calls. 

I think your problem is having the packages mixed up between the Python 3.10 and Blender. If you study your log above, you see both `C:/Users/45239/AppData/Roaming/Python/Python310` and `c:\program files\blender foundation\blender 3.6\3.6\python`. Everything should be running off of `c:\program files\blender foundation\blender 3.6\3.6\python` folder when you it under Blender.

I suggest printing the sys.path and make sure the blender python path is above the python 3.10. If not, insert/move the blender paths at the top.

**Comment by tin2tin** [comment]
I tried this, and there is no error importing the module, but it doesn't install ffmpeg, and print False:
```
import ffmpeg_downloader

ffmpeg_downloader.add_path()
print("Installed: " + str(ffmpeg_downloader.installed()))
```
The python is run from: c:\program files\blender foundation\blender 3.6\3.6\python - but placing ffdl here will Windows not allow. So, I properly got to figure out how to retrun to the path pip is using, and then execute ffdl from there: `C:/Users/45239/AppData/Roaming/Python/Python310` on user's computers.

**Comment by tin2tin** [comment]
I guess this should work, reusing the exact path for installation destination and for executing ffdl, but it's erroring out with `access denied`. 

```
import subprocess, site, sys, os

app_path = site.USER_SITE
if app_path not in sys.path:
    sys.path.append(app_path)
pybin = sys.executable

dest_dir = site.getsitepackages()[0]
print("dest_dir: "+str(dest_dir))
print("app_path: "+str(app_path))
print("pybin: "+str(pybin))

subprocess.run(
    [
        pybin,
        "-m",
        "pip",
        "install",
        "ffmpeg-downloader",
        "--target",
        dest_dir,
    ]
)

subprocess.run([
    dest_dir,
    "ffdl",
    "install",
    "--add-path"
])

import ffmpeg_downloader

print("Installed: " + str(ffmpeg_downloader.installed()))
```

**Comment by tikuma-lsuhsc** [comment]
Check out this post. This maybe exactly what you need to fix your situation

https://b3d.interplanety.org/en/installing-python-packages-with-pip-in-blender-on-windows-10/
